name: CI (Windows)

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'
        required: true
# on:
#   push:
#     paths:
#     - '3rdparty/**'
#     - 'scripts/**'
#     - 'src/**'
#     - 'COPYING'
#     - 'makefile'
#   pull_request:
#     paths:
#     - '3rdparty/**'
#     - 'scripts/**'
#     - 'src/**'
#     - 'COPYING'
#     - 'makefile'

permissions:
  contents: read

jobs:

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        install: git make mingw-w64-x86_64-gcc mingw-w64-x86_64-python mingw-w64-x86_64-lld mingw-w64-x86_64-libc++
    - uses: actions/checkout@master
    - name: Build
      env:
        MINGW64: "/mingw64"
        OVERRIDE_AR: "llvm-ar"
        OVERRIDE_CC: gcc
        OVERRIDE_CXX: g++
        ARCHOPTS: "-fuse-ld=lld"
        SUBTARGET: neogeo
        SOURCES: "src/mame/neogeo"
        OPTIMIZE: 3
        DEPRECATED: 0
        NOWERROR: 1
        TOOLS: 1
        DEBUG: 0
      run: make -j9
    - uses: actions/upload-artifact@master
      with:
        name: neogeo-windows-${{ github.event.inputs.tag_name }}
        path: |
          neogeo.exe
          castool.exe
          chdman.exe
          floptool.exe
          imgtool.exe
          jedutil.exe
          ldresample.exe
          ldverify.exe
          ledutil.exe
          nltool.exe
          nlwav.exe
          pngcmp.exe
          regrep.exe
          romcmp.exe
          split.exe
          srcclean.exe
          unidasm.exe
